pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..PROJ'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..PROJ'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....PROJ'
            }
        }
    }
}
